name: TacoAPI
main: com.kill3rtaco.tacoapi.TacoAPI
description: A plugin API inspired by DeityAPI
version: 2.5.4
load: startup
authors: [KILL3RTACO]
softdepend: [ItemMail, WorldEdit, Vault]
commands:
  dev:
    aliases: [developer, d, ta]